### ISSUE TITLE
Don't weird log and cannot access 401 error. 

### ISSUE THREAD

**Issue by apereira435** [Cloud-Temple/Mattermost-client#8]
Example config 

```
host :"localhost:8065" 
token: "8gbmmixh3prcfp6du1qbngt3mh"
```
I get this constant log. 
```
Feb 27, 2021 10:50:47 AM com.cloudtemple.mattermost.WsSocketListener onOpen
INFO: [ws] opened
Feb 27, 2021 10:50:47 AM com.cloudtemple.mattermost.WsSocketListener onOpen
INFO: [ws] opened
Feb 27, 2021 10:50:52 AM com.cloudtemple.mattermost.WsSocketListener onClose
INFO: [ws] closed
Feb 27, 2021 10:50:52 AM com.cloudtemple.mattermost.WebSocketClient$1 onClose
INFO: [ws] reconnect
Feb 27, 2021 10:50:52 AM com.cloudtemple.mattermost.WsSocketListener onOpen
INFO: [ws] opened
Feb 27, 2021 10:50:52 AM com.cloudtemple.mattermost.WsSocketListener onOpen
INFO: [ws] opened
```
And everytime I want to access something I get this `401 Invalid or expired session, please login again.` I read your setup but I don't get why it should help, I used a different driver with similar configuration and it worked, I changed to use your driver because I wanted to be able to use wesockets. 

Most of the settings you mentioned I already setup, I created a bot account with access token. 

 I need to use mattermostbotclient without having to setup anything on the server, and access it with just the bot token.

**Comment by Galigator** [comment]
Hello apereira435, I have develop this simple bot client to be able to use mattermost 4.5 and without changes it have been working nicely with the 4.9 too. Since I have move to another chat tool I don't have update this lib for the new version.
Maybe newest version don't require the settings I have done server side, but when I have done it, I remember that was the only way to make it work.

Also your the error you get are really close to the errors of https://github.com/Galigator/Mattermost-client/issues/1 . Maybe the same solution will work.

**Comment by apereira435** [comment]
Hi there I will close since I fixed the issue by creating another token and using that one but got another problem with json mapping exception. I totally understand that what you said, I forked the repo and will try to fix this and other issues and possibly do a pull request if you want to merge. 
Thanks.
